"""empty message

Revision ID: 117240b96618
Revises: 5713f0263f32
Create Date: 2023-10-28 16:03:20.234217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117240b96618'
down_revision = '5713f0263f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
