"""empty message

Revision ID: 4bfc585aee26
Revises: 2baa0ea606c3
Create Date: 2023-10-23 14:00:16.115840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfc585aee26'
down_revision = '2baa0ea606c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.drop_column('completion_status')

    with op.batch_alter_table('to_do_items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('importance', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_items_table', schema=None) as batch_op:
        batch_op.drop_column('importance')
        batch_op.drop_column('urgency')

    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_status', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
