"""empty message

Revision ID: 5713f0263f32
Revises: 4bfc585aee26
Create Date: 2023-10-24 11:22:41.510194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5713f0263f32'
down_revision = '4bfc585aee26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('usage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_locations_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations_table'))
    )
    op.drop_table('shop_locations_table')
    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_events_table_location_id_locations_table'), 'locations_table', ['location_id'], ['id'])
        batch_op.drop_column('location')

    with op.batch_alter_table('shopping_items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shopping_items_table_location_id_locations_table'), 'locations_table', ['location_id'], ['id'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_shopping_items_table_location_id_locations_table'), type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('events_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_events_table_location_id_locations_table'), type_='foreignkey')
        batch_op.drop_column('location_id')

    op.create_table('shop_locations_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('usage', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name='fk_shop_locations_table_user_id_users_table'),
    sa.PrimaryKeyConstraint('id', name='pk_shop_locations_table')
    )
    op.drop_table('locations_table')
    # ### end Alembic commands ###
