"""empty message

Revision ID: 758934f85fb7
Revises: 06020a4850b8
Create Date: 2023-10-23 11:56:11.713704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758934f85fb7'
down_revision = '06020a4850b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('repeats', sa.String(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_events_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_locations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('usage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_shop_locations_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_items_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_shopping_items_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_do_lists_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('repeats', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_to_do_lists_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_do_items_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toDoList_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_table.id'], name=op.f('fk_to_do_items_table_event_id_events_table')),
    sa.ForeignKeyConstraint(['toDoList_id'], ['to_do_lists_table.id'], name=op.f('fk_to_do_items_table_toDoList_id_to_do_lists_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_do_items_table')
    op.drop_table('to_do_lists_table')
    op.drop_table('shopping_items_table')
    op.drop_table('shop_locations_table')
    op.drop_table('events_table')
    # ### end Alembic commands ###
